# Generated by Django 5.0.6 on 2024-08-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdetailes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('firstname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Adharno', models.BigIntegerField()),
                ('panno', models.CharField(max_length=100)),
                ('Emailid', models.EmailField(max_length=254)),
                ('place', models.CharField(max_length=100)),
                ('contactno', models.BigIntegerField()),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
